// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function SetInitialFile(arg1) {
  return window['go']['main']['App']['SetInitialFile'](arg1);
}

export function SetSettingsService(arg1) {
  return window['go']['main']['App']['SetSettingsService'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
