// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetInitialFile():Promise<string>;

export function SetInitialFile(arg1:string):Promise<void>;

export function SetSettingsService(arg1:main.SettingsService):Promise<void>;

export function ToggleFullscreen():Promise<void>;
