// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileTree(arg1) {
  return window['go']['main']['FileService']['GetFileTree'](arg1);
}

export function OpenFile() {
  return window['go']['main']['FileService']['OpenFile']();
}

export function OpenFolder() {
  return window['go']['main']['FileService']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['FileService']['ReadFile'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['FileService']['SetContext'](arg1);
}

export function SetSettingsService(arg1) {
  return window['go']['main']['FileService']['SetSettingsService'](arg1);
}
