// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function GetFileTree(arg1:string):Promise<main.FolderResult>;

export function OpenFile():Promise<main.FileResult>;

export function OpenFolder():Promise<main.FolderResult>;

export function ReadFile(arg1:string):Promise<main.FileResult>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetSettingsService(arg1:main.SettingsService):Promise<void>;
