// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1) {
  return window['go']['main']['SettingsService']['AddBookmark'](arg1);
}

export function AddRecentFile(arg1) {
  return window['go']['main']['SettingsService']['AddRecentFile'](arg1);
}

export function ClearRecentFiles() {
  return window['go']['main']['SettingsService']['ClearRecentFiles']();
}

export function GetBookmarks() {
  return window['go']['main']['SettingsService']['GetBookmarks']();
}

export function GetReadingProgress(arg1) {
  return window['go']['main']['SettingsService']['GetReadingProgress'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['SettingsService']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['SettingsService']['GetSettings']();
}

export function GetWindowState() {
  return window['go']['main']['SettingsService']['GetWindowState']();
}

export function IsBookmarked(arg1) {
  return window['go']['main']['SettingsService']['IsBookmarked'](arg1);
}

export function Load() {
  return window['go']['main']['SettingsService']['Load']();
}

export function RemoveBookmark(arg1) {
  return window['go']['main']['SettingsService']['RemoveBookmark'](arg1);
}

export function Save() {
  return window['go']['main']['SettingsService']['Save']();
}

export function SaveReadingProgress(arg1, arg2) {
  return window['go']['main']['SettingsService']['SaveReadingProgress'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['SettingsService']['SaveSettings'](arg1);
}

export function SaveWindowState(arg1) {
  return window['go']['main']['SettingsService']['SaveWindowState'](arg1);
}

export function SetConfigPath(arg1) {
  return window['go']['main']['SettingsService']['SetConfigPath'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['SettingsService']['SetContext'](arg1);
}
