// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddBookmark(arg1:string):Promise<void>;

export function AddRecentFile(arg1:string):Promise<void>;

export function ClearRecentFiles():Promise<void>;

export function GetBookmarks():Promise<Array<string>>;

export function GetReadingProgress(arg1:string):Promise<number>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetSettings():Promise<main.Settings>;

export function GetWindowState():Promise<main.WindowState>;

export function IsBookmarked(arg1:string):Promise<boolean>;

export function Load():Promise<void>;

export function RemoveBookmark(arg1:string):Promise<void>;

export function Save():Promise<void>;

export function SaveReadingProgress(arg1:string,arg2:number):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SaveWindowState(arg1:main.WindowState):Promise<void>;

export function SetConfigPath(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
